/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 stadium3.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stadium3(props) {
  const { nodes, materials } = useGLTF('./background/stadium3.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Cube.geometry} material={materials.Material} />
      <group position={[-86.069, 42.434, -0.396]} rotation={[-Math.PI / 2, 0, 0]} scale={[1.82, 14.335, 5.62]}>
        <mesh geometry={nodes.Cube020_Material129_0.geometry} material={materials['Material.129']} />
        <mesh geometry={nodes.Cube020_Material129_0001.geometry} material={materials['Material.129']} />
      </group>
      <group position={[85.285, 42.434, -0.413]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[1.82, 14.335, 5.62]}>
        <mesh geometry={nodes.Cube021_Material130_0.geometry} material={materials['Material.130']} />
        <mesh geometry={nodes.Cube021_Material130_0001.geometry} material={materials['Material.130']} />
      </group>
      <mesh geometry={nodes.Cube_Material099_0.geometry} material={materials['Material.099']} position={[-0.219, 37.926, 74.52]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 3.913, 1.533]} />
      <mesh geometry={nodes.Cube001_Material100_0.geometry} material={materials['Material.100']} position={[-0.219, 37.926, -75.49]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 3.913, 1.533]} />
      <mesh geometry={nodes.Cube002_Material101_0.geometry} material={materials['Material.101']} position={[96.226, 37.926, -0.51]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[79.039, 3.913, 1.533]} />
      <mesh geometry={nodes.Cube003_Material102_0.geometry} material={materials['Material.102']} position={[-96.749, 37.926, -0.51]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[79.039, 3.913, 1.533]} />
      <mesh geometry={nodes.Cube004__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 44.436, 75.323]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube005__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 44.436, -76.526]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube006__0.geometry} material={materials['Cube.004__0']} position={[95.614, 44.436, -0.542]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube007__0.geometry} material={materials['Cube.004__0']} position={[-96.545, 44.436, -0.542]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube009__0.geometry} material={materials['Cube.004__0']} position={[95.614, 53.739, -0.542]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube010__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 53.739, -76.526]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube011__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 53.739, 75.323]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube008__0.geometry} material={materials['Cube.004__0']} position={[-96.545, 53.739, -0.542]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube013__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 63.103, -76.526]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube014__0.geometry} material={materials['Cube.004__0']} position={[95.614, 63.103, -0.542]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube015__0.geometry} material={materials['Cube.004__0']} position={[-96.545, 63.103, -0.542]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube012__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 63.103, 75.323]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube017__0.geometry} material={materials['Cube.004__0']} position={[95.614, 72.55, -0.542]} rotation={[-Math.PI / 2, 0, Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube018__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 72.55, -76.526]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube019__0.geometry} material={materials['Cube.004__0']} position={[-0.219, 72.55, 75.323]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 2.763, 4.853]} />
      <mesh geometry={nodes.Cube016__0.geometry} material={materials['Cube.004__0']} position={[-96.545, 72.55, -0.542]} rotation={[-Math.PI / 2, 0, -Math.PI / 2]} scale={[75.643, 2.763, 4.853]} />
      <mesh geometry={nodes.Cylinder__0.geometry} material={materials['Cube.004__0']} position={[-84.532, 42.424, -14.769]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.377, 0.377, 5.682]} />
      <mesh geometry={nodes.Cylinder001__0.geometry} material={materials['Cube.004__0']} position={[-84.532, 42.424, 13.952]} rotation={[-Math.PI / 2, 0, 0]} scale={[0.377, 0.377, 5.682]} />
      <mesh geometry={nodes.Cylinder002__0.geometry} material={materials['Cube.004__0']} position={[-84.532, 48.071, -0.405]} rotation={[-Math.PI, 0, 0]} scale={[0.377, 0.377, 14.623]} />
      <mesh geometry={nodes.Cylinder003__0.geometry} material={materials['Cube.004__0']} position={[83.748, 48.071, -0.403]} rotation={[0, 0, -Math.PI]} scale={[0.377, 0.377, 14.623]} />
      <mesh geometry={nodes.Cylinder004__0.geometry} material={materials['Cube.004__0']} position={[83.748, 42.424, -14.761]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.377, 0.377, 5.682]} />
      <mesh geometry={nodes.Cylinder005__0.geometry} material={materials['Cube.004__0']} position={[83.748, 42.424, 13.96]} rotation={[-Math.PI / 2, 0, Math.PI]} scale={[0.377, 0.377, 5.682]} />
      <mesh geometry={nodes.Plane_Material098_0.geometry} material={materials['Material.098']} position={[-0.219, 36.999, -0.379]} rotation={[-Math.PI / 2, 0, 0]} scale={[92.624, 71.011, 30.875]} />
      <mesh geometry={nodes.Plane001_Material131_0.geometry} material={materials['Material.131']} position={[0, 53.346, -72.556]} scale={[16.189, 3.74, 3.74]} />
    </group>
  )
}

useGLTF.preload('./background/stadium3.glb')
