/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.2.13 stadium.glb 
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Stadium(props) {
  const { nodes, materials } = useGLTF('./background/stadium.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Ground.geometry} material={materials['Grey.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Rails_Extra.geometry} material={materials['Orange Light']} position={[34.802, 0.001, 54.591]} scale={[1.259, 1, 1]} />
      <mesh geometry={nodes.Outer_Supports002.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Back_Poles.geometry} material={materials['Orange Dark']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.behindstands.geometry} material={materials['Grey Darker']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Boundry.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Entrances001.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Field_01.geometry} material={materials['Green.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Field_02.geometry} material={materials['Green.001']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Field_Lines.geometry} material={materials['white Chalk']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Goals.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} rotation={[Math.PI / 2, 0, 0]} scale={0.032} />
      <mesh geometry={nodes.Gutter.geometry} material={materials.Grey} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Levels.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Net.geometry} material={materials.white} position={[34.791, 0.001, 54.591]} />
      <group position={[34.802, 0.001, 54.591]}>
        <mesh geometry={nodes.Cube011.geometry} material={materials['Grey Darker']} />
        <mesh geometry={nodes.Cube011_1.geometry} material={materials.Glass} />
      </group>
      <mesh geometry={nodes.Rails.geometry} material={materials['Orange Light']} position={[34.802, 0.001, 54.591]} scale={[1.259, 1, 1]} />
      <mesh geometry={nodes.Roof.geometry} material={materials['white.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Roof_Beams.geometry} material={materials['Grey Darker']} position={[34.802, 0.001, 54.591]} />
      <group position={[34.802, -3.44, 54.591]}>
        <mesh geometry={nodes.Cube014.geometry} material={materials.white} />
        <mesh geometry={nodes.Cube014_1.geometry} material={materials.Grey_Gloss} />
      </group>
      <group position={[34.802, 0.001, 54.591]}>
        <mesh geometry={nodes.Plane000.geometry} material={materials.Brown} />
        <mesh geometry={nodes.Plane000_1.geometry} material={materials['Orange Dark']} />
      </group>
      <mesh geometry={nodes.Stairs.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Stands.geometry} material={materials.Grey} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Steps.geometry} material={materials.white} position={[34.802, 4.891, 54.591]} />
      <mesh geometry={nodes.Steps001.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Suites.geometry} material={materials.white} position={[34.802, 0.051, 54.591]} />
      <group position={[34.802, 0.001, 54.591]}>
        <mesh geometry={nodes.Cube067.geometry} material={materials.Glass} />
        <mesh geometry={nodes.Cube067_1.geometry} material={materials['Grey Darker']} />
      </group>
      <group position={[38.145, 0.226, 51.02]} scale={[0.7, 0.698, 0.7]}>
        <mesh geometry={nodes.Icosphere.geometry} material={materials.Ball_White} />
        <mesh geometry={nodes.Icosphere_1.geometry} material={materials.Ball_Black} />
      </group>
      <mesh geometry={nodes.Field_Outside.geometry} material={materials['Green.001']} position={[34.802, 0, 54.591]} />
      <mesh geometry={nodes.Entrances002.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_FIeld.geometry} material={materials['Green.001']} position={[34.802, 0, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Net.geometry} material={materials.white} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats_06.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats_08.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats02.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats03.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats04.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats05.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats07.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Low_Poly_Seats01.geometry} material={materials['Blue.002']} position={[34.802, 0.001, 54.591]} />
      <mesh geometry={nodes.Skydome.geometry} material={materials['Skydome Material']} position={[111.149, 11.003, 104.067]} rotation={[0, 0.609, 0]} scale={[800, 645.625, 800]} />
    </group>
  )
}

useGLTF.preload('./background/stadium.glb')
